language: java
jdk:
- openjdk11
deploy:
  provider: heroku
  api_key:
    secure: U1c/UR/lu332mVAJK6su1380ge4QSMmvyb0RMIqw9kUk33xWPm2fuoMoWIczacvQ6aNMXnEGh31Xs6cUnzIcNQnmZ2eRewi7cn104PgTRqq5nXCjV9vne9T7/V5ghQbO+hLtKVgC01AvADTQcp3434YYF+/tBh5oA3cJOAtUxUAP5hAux4OVSr3Lrull8yLMkbmyduKV/OGpJCN+IcdwIJsFsEj258u/uqJVG6EsBAJg+S9dgmw/GP7wSMPhi6M3lh6ekH48twp7FrO/WQ9W+wlob/usPRMhvLSVw93QIeEqZ0FQlY/j4VI8UyjDR3DxpFFd5rQxTJ/O8/GuFf7xZCmVQl1wO4XzjYFJVfo5i4XsjU+NDdR7eZJeIhUfYITf/UCpFCeu8WXpLXWvxHd487az+Jw1WfxqF8l7ofclIu/kkauuGrL97zV05J1VYo7CEdnByPSbcOeok+8qbLfQR81B36mW4PgPGRUhC6l17kOI7SuOKVZBIPC10xnDTKQzACws248RH0x+1Go+cdhes/vqw1zB/+VgCRzhGsVRCD9SjH0pOXLpeI/C4Bujlqxrfn7AbFTWInszLduN9i9Cf8m/gdh9uq7kglXO2hC+PXLAGTuE/Gpz+pEtnaM+FwyDppDPzsjI5bLZM5PWKYG+LBvT81woFk0a6kcL6J+ozTU=
  app: certificategenerator
