language: java
jdk:
- openjdk8
deploy:
  provider: heroku
  api_key:
    secure: MiuMEEwQZcQCmD7yjg8SEjYJDfXHpKLOn800D5WL1zyQPeG7Fg7LTWRcaWQqGGMYPF37+9aYt+VVSeO5EySgNFtoeGd/Nizxnp3Ex+NLjGrJLzK3AowfMeF10sUVTRExjvcAEta5z3QXCYJ+3WGp1KcLPaS3F1K8mT6WE2nO7Q1v4V33OiptQAjBp8pJTcSEzo5BtS4BqQ+vZfmQR2gk62VUcVW+7206vWPf+P0HfGOIkqyO3o6YPgcwm8I9B9CDWOfdrfqG6PgXAaUwBIFmThcX4NC3WkWFNjEZjwhgH0qu3xfUKbJkMJkHFoCKA7odrrSrl1FwRR++c54+hiTiFcwynxwRZnnp4N880QQi5tPieUpLb2LGZ7k54hFxjshLIo4rVwj7VdZvYRmlqs0neGjtjSgXjRc74MAXXqpdkog+y2UA6DJE0ViHi3c1lgoU5NVwiLXdxfEHHklP3+jw/yKhZP0n3HWPXbrnh/HRkufD7d0LmWmj9ww4cyoPFUu1nKzHylX28Vye6C1kGSCx3EGwRNLkgEqo7Atmw+yttOqKI6D0iNtxsWnNkknQnygMUyLqDjehwXW30PREaIOxRDPskbStODlhlFV6S1wOdtcXKznUR1WqMMxztlt+twsqe+5TNdl+A8xiwhaBHG6XRKP+aGoC7FPQ044QnG5uRTo=
  app: certificategenerator